# Generated by Django 5.0.3 on 2024-07-25 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='test_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
