# Generated by Django 5.0.3 on 2024-07-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0003_alter_mark_test_date_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
