# Generated by Django 5.0.3 on 2024-07-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0005_remove_mark_exam_name_alter_mark_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
